version: '3.9'

services:
  postgres:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pg-data:/var/lib/postgresql/data

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DB}
      MONGO_INITDB_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_PASSWORD: ${MONGO_PASSWORD}
    volumes:
      - mongodb-data:/data/db
      - ./init.d/mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh:ro

volumes:
  pg-data:
  mongodb-data:
