version: '3.9'

services:
  server:
    image: prakticum-server
    build:
      context: .
      dockerfile: Dockerfile.server
      args:
        SERVER_PORT: ${SERVER_PORT}
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_HOST: postgres
      MONGO_HOST: mongo
      VIRTUAL_HOST: ${APP_HOSTNAME}
      VIRTUAL_PORT: ${SERVER_PORT}
    depends_on:
      - postgres
      - mongo
    networks:
      - mynet

  nginx-proxy:
    image: nginxproxy/nginx-proxy
    container_name: nginx-proxy
    ports:
      - 80:80
      - 443:443
    volumes:
      - conf:/etc/nginx/conf.d
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - dhparam:/etc/nginx/dhparam
      - certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - mynet

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: nginx-proxy-le
    depends_on:
      - nginx-proxy
    volumes:
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - dhparam:/etc/nginx/dhparam:ro
      - certs:/etc/nginx/certs
      - acme:/etc/acme.sh
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - NGINX_PROXY_CONTAINER=nginx-proxy
    restart: always
    networks:
      - mynet

volumes:
  pg-data:
  mongodb-data:
  conf:
  vhost:
  html:
  dhparam:
  certs:
  acme:

networks:
  mynet:
    name: tanchiki_default
    external: true
