export enum Color {
  Yellow = 'YELLOW',
  Lime = 'LIME',
  Black = 'BLACK',
  Grey = '#636363',
  NormalGrey = 'GREY',
  LightGrey = 'LIGHTGREY',
  Orange = 'ORANGE',
  Red = 'RED',
  White = 'WHITE',
  Transparent = 'TRANSPARENT',
  LightCyan = 'LIGHTCYAN',
  Aqua = 'AQUA',
  Brown = 'BROWN',
  Green = 'GREEN',
  Blue = 'BLUE',
  AliceBlue = 'ALICEBLUE',
  Pink = '#483D8B',
}
