import { type FormInputAndHeadingList } from '../../app.typings';

export const userProfileFieldList: FormInputAndHeadingList = [
  {
    title: 'Email',
    type: 'email',
    id: 'email',
    validator: 'email',
    placeholder: 'ivan@mail.ru',
    required: true,
  },
  {
    title: 'Логин',
    type: 'text',
    id: 'login',
    validator: 'login',
    placeholder: 'Логин',
    required: true,
  },
  {
    title: 'Имя',
    type: 'text',
    id: 'first_name',
    validator: 'firstName',
    placeholder: 'Имя',
    required: false,
  },
  {
    title: 'Фамилия',
    type: 'text',
    id: 'second_name',
    validator: 'secondName',
    placeholder: 'Фамилия',
    required: false,
  },
  {
    title: 'Имя на форуме',
    type: 'text',
    id: 'display_name',
    validator: 'firstName',
    placeholder: 'Имя на форуме',
    required: false,
  },
  {
    title: 'Телефон',
    type: 'tel',
    id: 'phone',
    validator: 'phone',
    placeholder: '+7 800 555 35 35',
    required: true,
  },
  {
    heading: 'Если хотите поменять пароль:',
    id: 'passwordsTitle',
  },
  {
    title: 'Текущий пароль',
    type: 'password',
    id: 'oldPassword',
    validator: 'password',
    placeholder: 'Старый пароль',
    required: false,
  },
  {
    title: 'Новый пароль',
    type: 'password',
    id: 'newPassword',
    validator: 'password',
    placeholder: 'Новый пароль',
    required: false,
  },
  {
    heading: 'Если хотите поменять аватар:',
    id: 'changeAvatarTitle',
  },
  {
    title: 'Фото',
    type: 'file',
    id: 'avatar',
    className: 'form-field_input-padding_lg',
  },
];
