name: telegram notification

# Controls when the workflow will run
on:
  # Triggers the workflow on pull request events but only for the "develop" branch
  pull_request:
    branches: ['develop']

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "notify"
  notify:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
      - name: Telegram notification
        uses: appleboy/telegram-action@master
        with:
          to: ${{secrets.TELEGRAM_CHAT_ID}}
          token: ${{secrets.TELEGRAM_TOKEN}}
          message: |
            ${{ github.actor }} создал новый Pull Request 🛠:
            📘 Название: ${{github.event.pull_request.title}}
            ✏️ Описание: ${{ github.event.pull_request.body }}


            👀 Посмотреть: ${{ github.event.pull_request.html_url}}
